```{r}
library(Seurat)
library(scater)
library(dplyr)
library(cowplot)
library(CellMixS)
```

# Technical QC

```{r}
pbmc_files = list()

for (file_name in list.files("../data", pattern = "txt"))
{
    file = read.delim(file.path("../data", file_name))
    rownames(file) = as.vector(file[,1]) %>% make.unique
    file = file[,-c(1,2)]
    pbmc = CreateSeuratObject(counts = file, min.cells = 5, min.features = 200)
    
    ##### QC
    # Check for % of mitotic genes
    # FeatureScatter is typically used to visualize feature-feature relationships, but can be used
    # for anything calculated by the object, i.e. columns in object metadata, PC scores etc.
    pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^mt-")
    plot1 = FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt",)
    plot2 = FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
    plot3 = VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
    pbmc_files[[paste(file_name)]] = list(pbmc = pbmc,
                                          plots_SO_before_filtering = plot_grid(plot1, plot2, plot3, nrow = 3, labels = file_name))
    message(file_name)
}
```

```{r}
                    # Filtering based on SO

for (i in 1:length(pbmc_files))
{
    pbmc = pbmc_files[[i]][["pbmc"]]
    
    # Insert parameters 
    if (i == 1)
    {
        message(paste("Insert the following values for filtering"))
        nfeature_lower = as.integer(readline("min number of feature "))
        nfeature_upper = as.integer(readline("max number of feature "))
        perc_mitotic = as.integer(readline("max percentage of mitotic genes "))
        ncount = as.integer(readline("min number of counts to keep "))
    }

    # Subset SO 
    pbmc = subset(pbmc, subset = nFeature_RNA > nfeature_lower & 
                  nFeature_RNA < nfeature_upper & 
                  percent.mt < perc_mitotic &
                 nCount_RNA > ncount)
    
    # Subset SO with nCount which are between median - 1.5starndart deviation and median + 1.5sd 
    pbmc = subset(pbmc, subset = 
            nCount_RNA < median(pbmc@meta.data$nCount_RNA) + 1.5 * sd(pbmc@meta.data$nCount_RNA) &
            nCount_RNA > median(pbmc@meta.data$nCount_RNA) - 1.5 * sd(pbmc@meta.data$nCount_RNA))
    
    pbmc_files[[i]][["pbmc"]] = pbmc
    
    # Create plots with plots post-filtering
    pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^mt-")
    plot1 = FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt",)
    plot2 = FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
    plot3 = VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
    pbmc_files[[i]][["plots_SO_after_filtering"]] = plot_grid(plot1, plot2, plot3, nrow = 3, labels = names(pbmc_files)[i])
    
}

# Save as pdf non-filtered data sets (1 page per data set)
pdf("plots_SO_after_filtering.pdf")
    for (i in 1:length(pbmc_files))
    {
        print(pbmc_files[[i]][["plots_SO_after_filtering"]])
    }
dev.off()
message("plots saved as pdf! Check them")

# We filtering according to the following criteria:
# nfeature_lower = 1000
# nfeature_upper = 6000
# perc_mitotic = 8
# ncount = 50000
```

```{r}
                    # Create single cell Experiment for scater and create plots

for (i in 1:length(pbmc_files))
{
    pbmc.sce = as.SingleCellExperiment(x = pbmc_files[[i]][["pbmc"]])

    pbmc.sce <- calculateQCMetrics(pbmc.sce)

    plot1 = plotExprsFreqVsMean(pbmc.sce)
    plot2 = plotScater(pbmc.sce, colour_by = "ident", nfeatures = 500, exprs_values = "counts")
    pbmc_files[[i]][["plots_scater"]] = plot_grid(plot1, plot2, nrow = 2, labels = names(pbmc_files)[i])
    
}

# Save as pdf non-filtered data sets (1 page per data set)
pdf("plots_scater.pdf")
    for (i in 1:length(pbmc_files))
    {
        print(pbmc_files[[i]][["plots_scater"]])
    }
dev.off()
message("Scater plots saved as pdf! Check them")
```

```{r}
                # Filtering based on scater (we only analyzed 2 plots)

for (i in 1:length(pbmc_files))
{
    pbmc = pbmc_files[[i]][["pbmc"]]
    
    # Filtering according to plotScateer
    pbmc.sce = as.SingleCellExperiment(x = pbmc)

    pbmc.sce <- calculateQCMetrics(pbmc.sce)
    
    # Eliminate cells in which 500 features account for more than 95% of library
    x = plotScater(pbmc.sce, colour_by = "ident", nfeatures = 500, exprs_values = "counts")
    y = x$data[which(x$data$Feature == 500 & x$data$Proportion_Library > 0.95 ),]
    
    # Subset SO
    if (dim(y)[1] != 0)
    {
        cells_keep = Cells(pbmc)[-y$Cell]
        pbmc = subset(pbmc, cells = cells_keep)
    }
    
    pbmc_files[[i]][["pbmc"]] = pbmc
}
```

```{r}
# Sum the total number of cells in the end
a = 0
for (i in 1:7)
{
    x = print(Cells(pbmc_files[[i]]$pbmc) %>% length)
    a = a + x
}
a
```

# Seurat integration of all data sets

```{r}
# Normalize and Compute Variable features for each dataset separately
for (i in 1:length(pbmc_files)) 
{
    pbmc_files[[i]][["pbmc"]] <- NormalizeData(pbmc_files[[i]][["pbmc"]], verbose = FALSE)
    pbmc_files[[i]][["pbmc"]] <- FindVariableFeatures(pbmc_files[[i]][["pbmc"]], selection.method = "vst", 
        nfeatures = 2000, verbose = FALSE)
}
```

```{r}
                    # Perform integration

# Create a list with pbmc objects
SO = list()
for (i in 1:length(pbmc_files)) 
{
    SO[[i]] = pbmc_files[[names(pbmc_files)[i]]][["pbmc"]]
    names(SO)[[i]] = names(pbmc_files)[i]
}

# Here use k = 50 since one of dataset has only 63 cells and will give an error in this step
pbmc_anchors <- FindIntegrationAnchors(object.list = SO, dims = 1:30, k.filter = 50, anchor.features = 2000)

SO <- IntegrateData(anchorset = pbmc_anchors, dims = 1:30)
```

```{r}
DefaultAssay(SO) <- "integrated"
n_PC = 1:15

SO = FindVariableFeatures(SO, selection.method = "vst", nfeatures = 2000)

# Run the standard workflow for visualization and clustering
SO <- ScaleData(SO, verbose = FALSE)
SO <- RunPCA(SO, npcs = 30, verbose = FALSE, set.seed = 3)
# t-SNE and Clustering
SO <- FindNeighbors(SO, reduction = "pca", dims = n_PC, set.seed = 3)
SO <- FindClusters(SO, resolution = 0.6, set.seed = 3)
SO <- RunTSNE(SO, reduction = "pca", dims = n_PC,set.seed = 3)
SO <- RunUMAP(SO, reduction = "pca", dims = n_PC, set.seed = 3)
```

# Batch effect

!!! Here we use Biologically filtered dataset 

## Non-corrected data

```{r}
load("../data/SO_Gli_Ascl_comb_int.Robj")
DefaultAssay(pbmc.combined) <- "RNA"

# Run the standard workflow for visualization and clustering
pbmc.combined <- ScaleData(pbmc.combined, verbose = FALSE)
pbmc.combined <- RunPCA(pbmc.combined, npcs = 30, verbose = FALSE, set.seed = 3)
# t-SNE and Clustering
pbmc.combined <- FindNeighbors(pbmc.combined, reduction = "pca", dims = 1:15, set.seed = 3)
pbmc.combined <- FindClusters(pbmc.combined, resolution = 0.6, set.seed = 3)
pbmc.combined <- RunTSNE(pbmc.combined, reduction = "pca", dims = 1:15,set.seed = 3)
pbmc.combined <- RunUMAP(pbmc.combined, reduction = "pca", dims = 1:15, set.seed = 3)
```

```{r}
# Compute cms

pbmc.combined.cell.type.sce = as.SingleCellExperiment(pbmc.combined)
pbmc.combined.cell.type.sce.cms <- cms(pbmc.combined.cell.type.sce,dim_red = "PCA", k =  175,group = "orig.ident", n_dim = 10, cell_min = 5 )
visOverview(pbmc.combined.cell.type.sce.cms, dim_red = "UMAP" , "batch_group")
```

```{r}
visHist(pbmc.combined.cell.type.sce.cms)
```

## Corrected data

```{r}
load("../data/SO_Gli_Ascl_comb_int.Robj")
```

```{r}
# Compute cms

pbmc.combined.cell.type.sce = as.SingleCellExperiment(pbmc.combined)
pbmc.combined.cell.type.sce.cms <- cms(pbmc.combined.cell.type.sce,dim_red = "PCA", k =  175,group = "orig.ident", n_dim = 10, cell_min = 5 )
visOverview(pbmc.combined.cell.type.sce.cms, dim_red = "UMAP" , "batch_group")
```
